# Default values for volume-s3
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: minio/minio:RELEASE.2018-07-23T18-34-49Z
aws_client_image: groundnuty/docker-aws:aws
imagePullPolicy: IfNotPresent
serviceType: ClusterIP

wait_for:
  image: groundnuty/k8s-wait-for:v1.5.1
  imagePullPolicy: IfNotPresent

# Specifies if init job should wait for s3 service to start
wait_for_s3:
  enabled: true

key_id: accessKey
access_key: verySecretKey
bucketName: test

port: 9000
log_file: /minio.log

# The generalization of nodeSelector.
# Allows for more fine grained controls over which
# nodes are selected by a kubernetes scheduler
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

# List of taints which are tolerated by the pods 
# when nodes are selected by a kubernetes scheduler
# https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# Specify a map of key-value pairs. For the pod 
# to be eligible to run on a node, the node 
# must have each of the indicated key-value pairs as labels
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}