apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ template "releaseName" .  }}
    heritage: {{ .Release.Service }}
    component: "cluster-manager"
  annotations:
    version: "{{ .Chart.Version }}"
data:
  CLUSTER-MANAGER_CONFIG: |-
    cluster-manager:
      domain: "{{ template "service_url" . }}"
  app.config: |-
    [
      % NOTE: this is needed to deploy oneprovider on distributed env on dockers
      % Range of ports that will be used by erlang nodes to communicate
      {kernel,[
          {inet_dist_listen_min, 9100},
          {inet_dist_listen_max, 9139}
      ]},

      %% SASL config
      {sasl, [{sasl_error_logger, false}]},

      %% logger configuration
      {lager, [
          {colored, true},
          {log_root, "./log"},
          {handlers, [
              %% show info level or higher level logs at console
              {lager_console_backend, [
                  {level, info}, {formatter, lager_default_formatter},
                  {formatter_config, [color, "[", sev, " ", time, " ", pid, "] ", message, "\e[0m\r\n"]}
              ]},
              %% rotate error log when it reaches 50 MB; keep 10 rotated logs
              {lager_file_backend, [
                  {file, "error.log"},
                  {level, error},
                  {size, 52428800},
                  {count, 10},
                  {formatter, lager_default_formatter},
                  {formatter_config, ["[", sev, " ", date, " ", time, " ", pid, "] ", message, "\n"]}
              ]},
              %% rotate info log when it reaches 50 MB; keep 10 rotated logs
              {lager_file_backend, [
                  {file, "info.log"},
                  {level, info},
                  {size, 52428800},
                  {count, 10},
                  {formatter, lager_default_formatter},
                  {formatter_config, ["[", sev, " ", date, " ", time, " ", pid, "] ", message, "\n"]}
              ]},
              %% rotate debug log when it reaches 50 MB; keep 10 rotated logs
              {lager_file_backend, [
                  {file, "debug.log"},
                  {level, debug},
                  {size, 52428800},
                  {count, 10},
                  {formatter, lager_default_formatter},
                  {formatter_config, ["[", sev, " ", date, " ", time, " ", pid, "] ", message, "\n"]}
              ]}
          ]},
          % Limit for the number of messages per second allowed from error_logger
          {error_logger_hwm, 200},
          % When lager should change mode to synchronous (log queue is longer than async_threshold)
          {async_threshold, 500},
          % When lager should return from synchronous mode to asynchronous (log queue is shorter than (async_threshold - async_threshold_window)
          {async_threshold_window, 50}
      ]},

      {ctool, [
          % Backup file that stores the information needed to restore the
          % previous clock synchronization.
          {clock_sync_backup_file, "./etc/time_synchronization_data.json"}
      ]},

      %% cluster_manager config
      {cluster_manager, [
          %% ===================================================================
          %% GENERAL
          %% ===================================================================

          %% How many worker nodes are expected to connect to cm - configured automatically by configurator.erl lib, used in GEN_DEV script
          {worker_num, {{ .Values.worker_num }} },
          % How often should load balancing advices be recomputed and sent to nodes [ms].
          {lb_advices_update_interval, 500},

          %% ===================================================================
          %% CLUSTER INIT STEPS
          %% ===================================================================

          {init_connection_step_timeout, 300000}, % 5 minutes
          {start_default_workers_step_timeout, 600000}, % 10 minutes
          {prepare_for_upgrade_step_timeout, 120000}, % 2 minutes
          {upgrade_cluster_step_timeout, 3600000}, % 1 hour
          {start_custom_workers_step_timeout, 300000}, % 5 minutes
          {db_and_workers_ready_step_timeout, 300000}, % 5 minutes
          {start_listeners_step_timeout, 120000}, % 2 minutes
          {cluster_ready_step_timeout, 120000}, % 2 minutes

          %% ===================================================================
          %% CLUSTER STATUS
          %% ===================================================================

          {cluster_status_caching_time_seconds, 15},
          {cluster_component_healthcheck_timeout, 10000} % 10 seconds
      ]}
    ].
