apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ template "releaseName" . }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
  annotations:
  {{- if .Values.deployAsPreInstallHook }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- end }}
    version: "{{ .Chart.Version }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: {{ template "fullname" . }}
