# Default values for onedata-3p.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

oz_image: &oz_image onedata/onezone:20.02.12
op_image: &op_image onedata/oneprovider:20.02.12
oc_image: &oc_image onedata/oneclient:20.02.12
cli_image: &cli_image onedata/rest-cli:20.02.12
luma_image: &luma_image onedata/luma:20.02.12
odfsj_image: &odfsj_image onedata/onedatafs-jupyter:20.02.12

log_level: &log_level "info"
onepanel_batch_mode_enabled: &onepanel_batch_mode_enabled true
oneclients_debug_mode_enabled: &oneclients_debug_mode_enabled false
onedata_anti_affinity_enabled: &onedata_anti_affinity_enabled false

oneproviders_generate_certificates: &oneproviders_generate_certificates false

oneproviders_nodes_count: &oneproviders_nodes_count 1
oneprovider_cluster_configs: &oneprovider_cluster_configs
  managers: [ ]
  workers: [ ]
  databases: [ ]

oneprovidersPanelOverlayConfig: &oneprovidersPanelOverlayConfig |-
  [].
oneprovidersWorkerOverlayConfig: &oneprovidersPanelOverlayConfig |-
  [].
  
oneclients_enabled: &oneclients_enabled true
onedata_cli_enabled: &onedata_cli_enabled true

luma_enabled: &luma_enabled false 

jupyter_notebook_enabled: &jupyter_notebook_enabled true

posix_enabled: &posix_enabled true
s3_enabled: &s3_enabled false
ceph_enabled: &ceph_enabled false
nfs_enabled: &nfs_enabled false
gluster_enabled: &gluster_enabled false
swift_enabled: &swift_enabled false
webdav_enabled: &webdav_enabled false
dcache_enabled: &dcache_enabled false

volume_data_sync_enabled: &volume_data_sync_enabled false

# Global luma configuration shared among providers
luma: &luma_global
  enabled: *luma_enabled
  image: *luma_image
  lumaCacheTimeout: 5
  lumaApiKey: example_api_key

  posix:
    enabled: &luma_enabled_posix true
    lowest_uid: 1000
    highest_uid: 65536
    
  s3:
    enabled: &luma_enabled_s3 false
    access_key: accessKey
    secret_key: verySecretKey

  ceph:
    enabled: &luma_enabled_ceph false
    pool_name: test
    username: client.k8s
    key: AQC1oSZZZfucFxAA34MekwoWBm7qpGd0A8u

  swift:
    enabled: &luma_enabled_swift false
    username: swift
    password: swift

  gluster:
    enabled: &luma_enabled_gluster false

  nfs:
    enabled: &luma_enabled_nfs false
    lowest_uid: 1000
    highest_uid: 65536

  webdav:
    enabled: &luma_enabled_webdav false

  dcache:
    enabled: &luma_enabled_dcache false

# Onezone configuration
onezone:
  image: *oz_image
  onepanel_batch_mode_enabled: *onepanel_batch_mode_enabled
  onedata_anti_affinity_enabled: *onedata_anti_affinity_enabled
  log_level: *log_level
  generate-certificates: 
    enabled: false
  onezone_nodes_count: 1
  cluster_config:
    managers: [ ]
    workers: [ ]
    databases: [ ]
  saml-idp:
    enabled: &idp_enabled true
    generate-certificates: 
      enabled: true
  panelOverlayConfig: |-
    [].
  workerOverlayConfig: |-
    [].

  token-dispenser:
    enabled: &token_dispenser_enabled true

# What follows are the providers configurations for providers designated as:
# krakow, paris, and lisbon
oneprovider-krakow:
  suffix: &op1s krakow
  geoLatitude: 50.0647
  geoLongitude: 19.9450

  image: *op_image
  onepanel_batch_mode_enabled: *onepanel_batch_mode_enabled
  onedata_anti_affinity_enabled: *onedata_anti_affinity_enabled
  log_level: *log_level
  nameOverride: oneprovider

  oneprovider_nodes_count: *oneproviders_nodes_count
  cluster_config: *oneprovider_cluster_configs

  panelOverlayConfig: *oneprovidersPanelOverlayConfig
  workerOverlayConfig: *oneprovidersPanelOverlayConfig

  onezone_service_url:
    type: auto-generate
    disableSuffix: true

  generate-certificates: 
    enabled: *oneproviders_generate_certificates

  luma:
    suffix: *op1s
    << : *luma_global

  volume-data-sync:
    enabled: *volume_data_sync_enabled

  oneclient:
    image: *oc_image
    debug_mode: *oneclients_debug_mode_enabled
    enabled: *oneclients_enabled
    suffix: *op1s
    onedata_cli:
      image: *cli_image
  jupyter-notebook:
    image: *odfsj_image
    enabled: *jupyter_notebook_enabled
    suffix: *op1s
  onedata-cli:
    image: *cli_image
    enabled: *onedata_cli_enabled
    suffix: *op1s
  posix:
    enabled: *posix_enabled
    luma-enabled: *luma_enabled_posix
  volume-s3:
    enabled: *s3_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_s3
  volume-ceph:
    enabled: *ceph_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_ceph
  volume-nfs:
    enabled: *nfs_enabled
    suffix: *op1s
    exports: &op1s-nfs-exports
    - name: empty
      luma-enabled: *luma_enabled_nfs
      readOnly: false
      storageClaim: 1T
  volume-gluster:
    enabled: *gluster_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_gluster
  volume-swift:
    enabled: *swift_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_swift
  volume-webdav:
    enabled: *webdav_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_webdav
  volume-dcache:
    enabled: *dcache_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_dcache

oneprovider-paris:
  suffix: &op2s paris
  geoLatitude: 48.8566
  geoLongitude: 2.3522

  image: *op_image
  onepanel_batch_mode_enabled: *onepanel_batch_mode_enabled
  onedata_anti_affinity_enabled: *onedata_anti_affinity_enabled
  log_level: *log_level
  nameOverride: oneprovider

  oneprovider_nodes_count: *oneproviders_nodes_count
  cluster_config: *oneprovider_cluster_configs

  panelOverlayConfig: *oneprovidersPanelOverlayConfig
  workerOverlayConfig: *oneprovidersPanelOverlayConfig

  onezone_service_url:
    type: auto-generate
    disableSuffix: true

  generate-certificates: 
    enabled: *oneproviders_generate_certificates

  luma:
    suffix: *op2s
    << : *luma_global

  volume-data-sync:
    enabled: *volume_data_sync_enabled
    
  oneclient:
    image: *oc_image
    debug_mode: *oneclients_debug_mode_enabled
    enabled: *oneclients_enabled
    suffix: *op2s
    onedata_cli:
      image: *cli_image
  jupyter-notebook:
    image: *odfsj_image
    enabled: *jupyter_notebook_enabled
    suffix: *op2s
  onedata-cli:
    image: *cli_image
    enabled: *onedata_cli_enabled
    suffix: *op2s
  posix:
    enabled: *posix_enabled
    luma-enabled: *luma_enabled_posix
  volume-s3:
    enabled: *s3_enabled
    suffix: *op2s
    luma-enabled: *luma_enabled_s3
  volume-ceph:
    enabled: *ceph_enabled
    suffix: *op2s
    luma-enabled: *luma_enabled_ceph
  volume-nfs:
    enabled: *nfs_enabled
    suffix: *op2s
    exports: &op2s-nfs-exports
    - name: empty
      luma-enabled: *luma_enabled_nfs
      readOnly: false
      storageClaim: 1T
    luma-enabled: *luma_enabled_nfs
  volume-gluster:
    enabled: *gluster_enabled
    suffix: *op2s
    luma-enabled: *luma_enabled_gluster
  volume-swift:
    enabled: *swift_enabled
    suffix: *op2s
    luma-enabled: *luma_enabled_swift
  volume-webdav:
    enabled: *webdav_enabled
    suffix: *op2s
    luma-enabled: *luma_enabled_webdav
  volume-dcache:
    enabled: *dcache_enabled
    suffix: *op2s
    luma-enabled: *luma_enabled_dcache

oneprovider-lisbon:
  suffix: &op3s lisbon
  geoLatitude: 38.7223
  geoLongitude: -9.1393

  image: *op_image
  onepanel_batch_mode_enabled: *onepanel_batch_mode_enabled
  onedata_anti_affinity_enabled: *onedata_anti_affinity_enabled
  log_level: *log_level
  nameOverride: oneprovider

  oneprovider_nodes_count: *oneproviders_nodes_count
  cluster_config: *oneprovider_cluster_configs

  panelOverlayConfig: *oneprovidersPanelOverlayConfig
  workerOverlayConfig: *oneprovidersPanelOverlayConfig

  onezone_service_url:
    type: auto-generate
    disableSuffix: true

  generate-certificates: 
    enabled: *oneproviders_generate_certificates

  luma:
    suffix: *op3s
    << : *luma_global

  volume-data-sync:
    enabled: *volume_data_sync_enabled

  oneclient:
    image: *oc_image
    debug_mode: *oneclients_debug_mode_enabled
    enabled: *oneclients_enabled
    suffix: *op3s
    onedata_cli:
      image: *cli_image
  jupyter-notebook:
    image: *odfsj_image
    enabled: *jupyter_notebook_enabled
    suffix: *op3s
  onedata-cli:
    image: *cli_image
    enabled: *onedata_cli_enabled
    suffix: *op3s
  posix:
    enabled: *posix_enabled
    luma-enabled: *luma_enabled_posix
  volume-s3:
    enabled: *s3_enabled
    suffix: *op3s
    luma-enabled: *luma_enabled_s3
  volume-ceph:
    enabled: *ceph_enabled
    suffix: *op3s
    luma-enabled: *luma_enabled_ceph
  volume-nfs:
    enabled: *nfs_enabled
    suffix: *op3s
    exports: &op3s-nfs-exports
    - name: empty
      luma-enabled: *luma_enabled_nfs
      readOnly: false
      storageClaim: 1T
  volume-gluster:
    enabled: *gluster_enabled
    suffix: *op3s
    luma-enabled: *luma_enabled_gluster
  volume-swift:
    enabled: *swift_enabled
    suffix: *op3s
    luma-enabled: *luma_enabled_swift
  volume-webdav:
    enabled: *webdav_enabled
    suffix: *op3s
    luma-enabled: *luma_enabled_webdav
  volume-dcache:
    enabled: *dcache_enabled
    suffix: *op3s
    luma-enabled: *luma_enabled_dcache

# Those variables are the unfortunate necessity of an issue discussed here:
# https://github.com/kubernetes/helm/issues/2479
token-dispenser:
  enabled: *token_dispenser_enabled
saml-idp:
  enabled: *idp_enabled
luma:
  enabled: *luma_enabled
oneclient:
  enabled: *oneclients_enabled
onedata-cli:
  enabled: *onedata_cli_enabled
volume-s3:
  enabled: *s3_enabled
volume-ceph:
  enabled: *ceph_enabled
volume-nfs:
  enabled: *nfs_enabled
volume-gluster:
  enabled: *gluster_enabled
volume-swift:
  enabled: *swift_enabled
volume-webdav:
  enabled: *webdav_enabled
volume-dcache:
  enabled: *dcache_enabled
volume-data-sync:
  enabled: *volume_data_sync_enabled