# Default values for onedata-1p.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

oz_image: &oz_image onedata/onezone:3.0.0-rc16
op_image: &op_image onedata/oneprovider:3.0.0-rc16
oc_image: &oc_image onedata/oneclient:3.0.0-rc16
cli_image: &cli_image onedata/rest-cli:3.0.0-rc16

log_level: &log_level "info"
onepanel_batch_mode_enabled: &onepanel_batch_mode_enabled true
oneclients_debug_mode_enabled: &oneclients_debug_mode_enabled false
onedata_anti_affinity_enabled: &onedata_anti_affinity_enabled false

oneproviders_nodes_count: &oneproviders_nodes_count 1
oneprovider_cluster_configs: &oneprovider_cluster_configs
  managers: [ ]
  workers: [ ]
  databases: [ ]

oneclients_enabled: &oneclients_enabled true
onedata_cli_enabled: &onedata_cli_enabled true

luma_enabled: &luma_enabled false 

swift_enabled: &swift_enabled false

# Those variables are the unfortunate necessity of an issue discussed here:
# https://github.com/kubernetes/helm/issues/2479
saml-idp:
  enabled: *idp_enabled
luma:
  enabled: *luma_enabled
oneclient:
  enabled: *oneclients_enabled
onedata-cli:
  enabled: *onedata_cli_enabled
volume-s3:
  enabled: *s3_enabled
volume-ceph:
  enabled: *ceph_enabled
volume-nfs:
  enabled: *nfs_enabled
volume-gluster:
  enabled: *gluster_enabled
volume-swift:
  enabled: *swift_enabled

# Global luma configuration shared among providers
luma: &luma_global
  enabled: *luma_enabled
  lumaCacheTimeout: 5
  lumaApiKey: example_api_key

  posix:
    enabled: &luma_enabled_posix true
    lowest_uid: 1000
    highest_uid: 65536
    
  s3:
    enabled: &luma_enabled_s3 false
    access_key: accessKey
    secret_key: verySecretKey

  ceph:
    enabled: &luma_enabled_ceph false
    pool_name: test
    username: client.k8s
    key: AQC1oSZZZfucFxAA34MekwoWBm7qpGd0A8u

  swift:
    enabled: &luma_enabled_swift false
    username: swift
    password: swift

  gluster:
    enabled: &luma_enabled_gluster false
      
  nfs:
    enabled: &luma_enabled_nfs false
    lowest_uid: 1000
    highest_uid: 65536

# Onezone configuration
onezone:
  image: *oz_image
  onepanel_batch_mode_enabled: *onepanel_batch_mode_enabled
  onedata_anti_affinity_enabled: *onedata_anti_affinity_enabled
  log_level: *log_level
  onezone_nodes_count: 1
  cluster_config:
    managers: [ ]
    workers: [ ]
    databases: [ ]
  saml-idp:
    enabled: &idp_enabled true

# What follows are the providers configurations for providers designated as:
# krakow
oneprovider-krakow:
  suffix: &op1s krakow
  geoLatitude: 50.0647
  geoLongitude: 19.9450

  image: *op_image
  onepanel_batch_mode_enabled: *onepanel_batch_mode_enabled
  onedata_anti_affinity_enabled: *onedata_anti_affinity_enabled
  log_level: *log_level
  nameOverride: oneprovider

  oneprovider_nodes_count: *oneproviders_nodes_count
  cluster_config: *oneprovider_cluster_configs

  onezone_service_url:
    type: auto-generate
    disableSuffix: true

  luma:
    suffix: *op1s
    << : *luma_global
  
  oneclient:
    image: *oc_image
    debug_mode: *oneclients_debug_mode_enabled
    enabled: *oneclients_enabled
    suffix: *op1s
    onedata_cli:
      image: *cli_image
  onedata-cli:
    image: *cli_image
    enabled: *onedata_cli_enabled
    suffix: *op1s
  posix:
    enabled: *posix_enabled
    luma-enabled: *luma_enabled_posix
  volume-s3:
    enabled: *s3_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_s3
  volume-ceph:
    enabled: *ceph_enabled
    luma-enabled: *luma_enabled_ceph
    suffix: *op1s
  volume-nfs:
    enabled: *nfs_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_nfs
  volume-gluster:
    enabled: *gluster_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_gluster
  volume-swift:
    enabled: *swift_enabled
    suffix: *op1s
    luma-enabled: *luma_enabled_swift