apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    onedata-service: "onezone"
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  serviceName: {{ template "fullname" . }}
  replicas: {{ .Values.onezone_nodes_count }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        onedata-service: "onezone"
      annotations:
        version: "{{ .Chart.Version }}"
    spec:
      subdomain: {{ template "fullname" . }}
      terminationGracePeriodSeconds: 0
      {{- if or .Values.affinity .Values.onedata_anti_affinity_enabled }}
      affinity:
      {{- if .Values.onedata_anti_affinity_enabled }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: onedata-service
                operator: In
                values:
                - oneprovider
                - onezone
              - key: release
                operator: In
                values:
                - {{ .Release.Name }}
            topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- if .Values.affinity }}
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
{{ include "imagePullSecrets" . | indent 6 }}
      {{- if (index .Values "generate-certificates" "enabled") }}
      initContainers:
        - name: certificate-init-container
          image: {{ index .Values "generate-certificates" "image" }}
          imagePullPolicy: {{ default .Values.imagePullPolicy .Values.global.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CERT_DIR
              value: /etc/tls
          command:
            - "/bin/sh"
            - "-c"
            - >
              if [[ $POD_NAME != {{ template "fullname" . }}-0 ]] ; then echo "Not generating certificates" ; exit 0 ; fi ;
              mkdir $(CERT_DIR) ;
              /certificate-init-container -secret-name={{ template "fullname" . }}-secret-tls -labels=app={{ template "fullname" . }},chart={{ .Chart.Name }},release={{ .Release.Name }},heritage={{ .Release.Service }} -additional-dnsnames={{ template "fullname" . }},{{ template "fullname" . }}.$(NAMESPACE),{{ template "fullname" . }}.$(NAMESPACE).svc -cert-dir=$(CERT_DIR) -namespace=$(NAMESPACE) -pod-ip=$(POD_IP) -pod-name=$(POD_NAME) -service-names={{ template "fullname" . }} -cluster-domain={{ template "cluster_domain" . }} ;
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ default .Values.imagePullPolicy .Values.global.imagePullPolicy | default "IfNotPresent" }}
        {{- if or .Values.cpu .Values.memory }}
        resources:
          requests:
          {{- if .Values.cpu }}
            cpu: {{ .Values.cpu }}
          {{- end }}
          {{- if .Values.memory }}
            memory: {{ .Values.memory }}
          {{- end }}
        {{- end }}
        ports:
          - containerPort: 53
          - containerPort: 80
          - containerPort: 443
          - containerPort: 5555
          - containerPort: 5556
          - containerPort: 6665
          - containerPort: 6666
          - containerPort: 7443
          - containerPort: 8443
          - containerPort: 8876
          - containerPort: 8877
          - containerPort: 9443
        command:
          - "/bin/bash"
          - "-c"
          - >
            echo {{ template "fullname" . }}-{{ sub (.Values.onezone_nodes_count) 1 }} ;
            if [[ "$HOSTNAME" != {{ template "fullname" . }}-{{ sub (.Values.onezone_nodes_count) 1 }} ]]; then export ONEPANEL_BATCH_MODE="false" ; fi ;
            env ;
            /root/onezone.sh ;
            cat /var/log/oz_panel/info.log ;
            exit 1 ;
        lifecycle:
          preStop:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  oz_panel stop ;
                  oz_worker stop ;
                  cluster_manager stop ;
                  /etc/init.d/couchbase-server stop ;
                  echo 1 > /monitor/onezone-exit ;
                  pkill -f onezone.py ;
        readinessProbe:
          initialDelaySeconds: 0
          periodSeconds: 1
          exec:
            # A hack, that makes sure that a pod reports ready when onezone has really started
            command:
              - "/bin/bash"
              - "-c"
              - >
                onepanel_ready() { sleep 5 ; exit 0 ; } ;
                if [[ "$HOSTNAME" == {{ template "fullname" . }}-{{ sub (.Values.onezone_nodes_count) 1 }} ]]; then exit 0 ; else onepanel_ready ; fi ;
        env:
          - name: ONEPANEL_LOG_LEVEL
            value: {{ default .Values.log_level "info" | quote }}
          - name: ONEPANEL_BATCH_MODE
            value: {{ .Values.onepanel_batch_mode_enabled | quote }}
          - name: ONEZONE_CONFIG
            value: |
              cluster:
                domainName: "{{ template "service_url" . }}"
                nodes:
                  {{- $r := . -}}
                  {{- range $i := until (int (.Values.onezone_nodes_count)) }}
                  n{{ $i }}: 
                    hostname: {{ template "fullname" $r }}-{{ $i }}
                  {{- end }}
                managers:
                  mainNode: n{{ sub (.Values.onezone_nodes_count) 1 }} 
                  nodes:
              {{- with .Values.cluster_config.managers }}
                  {{- range $i := . }}
                    - n{{ $i }}
                  {{- end }}
              {{- else }}
                  {{- range $i := until (int ($r.Values.onezone_nodes_count)) }}
                    - n{{ $i }}
                  {{- end }}
              {{- end }}
                workers:
                  nodes:
              {{- with .Values.cluster_config.workers }}
                  {{- range $i := . }}
                    - n{{ $i }}
                  {{- end }}
              {{- else }}
                  {{- range $i := until (int ($r.Values.onezone_nodes_count)) }}
                    - n{{ $i }}
                  {{- end }}
              {{- end }}
                databases:
                  nodes:
              {{- with .Values.cluster_config.databases }}
                  {{- range $i := . }}
                    - n{{ $i }}
                  {{- end }}
              {{- else }}
                  {{- range $i := until (int ($r.Values.onezone_nodes_count)) }}
                    - n{{ $i }}
                  {{- end }}
              {{- end }}
              onezone:
                {{ if .Values.name -}}
                name: {{ .Values.name }}
                {{- else -}}
                name: {{ template "fullname" . }}
                {{- end }}
                domainName: {{ template "service_url" . }}
              {{- if or .Values.onepanel_admin_users .Values.onepanel_users }}
              onepanel:
                users:
                  {{- range .Values.onepanel_admin_users }}
                  {{ .login }}:
                    password: {{ .password }}
                    userRole: admin
                  {{- end }}
                  {{- range .Values.onepanel_users }}
                  {{ .login }}:
                    password: {{ .password }}
                    userRole: regular
                  {{- end }}
              {{- end }}
      {{- if or (index .Values "generate-certificates" "enabled") (index .Values "saml-idp" "enabled")}}
        volumeMounts:
      {{- end }}
      {{- if (index .Values "generate-certificates" "enabled") }}
          - mountPath: /etc/oz_panel/certs/key.pem
            subPath: tls.key
            name: tls
            readOnly: true
          - mountPath: /etc/oz_panel/certs/cert.pem
            subPath: tls.crt
            name: tls
            readOnly: true
          - mountPath: /etc/oz_panel/cacerts/cacert.pem
            subPath: k8s.crt
            name: tls
            readOnly: true
          - mountPath: /etc/oz_worker/cacerts/cacert.pem
            subPath: k8s.crt
            name: tls
            readOnly: true
          - mountPath: /etc/ssl/certs/kubernetes.crt
            subPath: k8s.crt
            name: tls
            readOnly: true
    {{- end }}
    {{- if (index .Values "saml-idp" "enabled") }}
          - mountPath: /var/lib/oz_worker/saml.config
            subPath: saml.config
            name: saml-config
            readOnly: false
    {{- end }}
    {{- if or (index .Values "generate-certificates" "enabled") (index .Values "saml-idp" "enabled")}}
      volumes:
    {{- end }}
    {{- if (index .Values "generate-certificates" "enabled") }}
      - name: tls
        secret:
          secretName: {{ template "fullname" . }}-secret-tls
    {{- end }}
    {{- if (index .Values "saml-idp" "enabled") }}
      - name: saml-config
        configMap:
          name: {{ template "fullname" . }}-saml-config
    {{- end }}