# Default values for oneclient.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: onedata/oneclient:17.06.0-rc1
imagePullPolicy: IfNotPresent
number_of_oneclients: 1

wait_for:
  image: onedata/k8s-wait-for:v1.0.1
  imagePullPolicy: IfNotPresent

onedata_cli:
  image: onedata/rest-cli:17.06.0-beta6
  imagePullPolicy: IfNotPresent

# by default the main process in a onezone container is
# a oneclient command running in foreground
# this flag takes oneclient to background and launches
# while sleep loop as primary container process
debug_mode: true
