apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ template "releaseName" . }}
    heritage: {{ .Release.Service }}
    onedata-service: "oneprovider"
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  serviceName: {{ template "fullname" . }}
  replicas: {{ .Values.oneprovider_nodes_count }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: {{ .Chart.Name }}
        release: {{ template "releaseName" . }}
        heritage: {{ .Release.Service }}
        onedata-service: "oneprovider"
      annotations:
        version: "{{ .Chart.Version }}"
    spec:
      subdomain: {{ template "fullname" . }}
      hostNetwork: {{ template "hostNetwork" . }}
      terminationGracePeriodSeconds: 0
      {{- if or .Values.affinity .Values.onedata_anti_affinity_enabled }}
      affinity:
      {{- if .Values.onedata_anti_affinity_enabled }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: onedata-service
                operator: In
                values:
                - oneprovider
                - onezone
              - key: release
                operator: In
                values:
                - {{ template "releaseName" . }}
            topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- if .Values.affinity }}
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
{{ include "imagePullSecrets" . | indent 6 }}
      {{- if or (eq (int .Values.oneprovider_nodes_count) 1) (or (index .Values "volume-s3" "enabled")) (or (index .Values "volume-ceph" "enabled") (or (index .Values "volume-gluster" "enabled") (or (index .Values "volume-swift" "enabled") (index .Values "generate-certificates" "enabled")))) }}
      initContainers:
      {{- end }}
      {{- if (index .Values "generate-certificates" "enabled") }}
        - name: certificate-init-container
          image: {{ index .Values "generate-certificates" "image" }}
          imagePullPolicy: {{ template "imagePullPolicy" dict "root" . "context" (index .Values "generate-certificates") }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CERT_DIR
              value: /etc/tls
          command:
            - "/bin/sh"
            - "-c"
            - >
              if [[ $POD_NAME != {{ template "fullname" . }}-0 ]] ; then echo "Not generating certificates" ; exit 0 ; fi ;
              mkdir $(CERT_DIR) ;
              /certificate-init-container -secret-name={{ template "fullname" . }}-secret-tls -labels=app={{ template "fullname" . }},chart={{ .Chart.Name }},release={{ template "releaseName" . }},heritage={{ .Release.Service }} -additional-dnsnames={{ template "fullname" . }},{{ template "fullname" . }}.$(NAMESPACE),{{ template "fullname" . }}.$(NAMESPACE).svc -cert-dir=$(CERT_DIR) -namespace=$(NAMESPACE) -pod-ip=$(POD_IP) -pod-name=$(POD_NAME) -service-names={{ template "fullname" . }} -cluster-domain={{ template "cluster_domain" . }} ;
      {{- end }}
      {{- if (index .Values "volume-s3" "enabled") }}
        - name: wait-for-volume-s3-init
          image: {{ .Values.wait_for.image }}
          imagePullPolicy: {{ template "imagePullPolicy" dict "root" . "context" .Values.wait_for }}
          args:
            - "job"
            - "{{ template "volume-s3_name" . }}-init"
      {{- end }}
      {{- if (index .Values "volume-ceph" "enabled") }}
        - name: wait-for-volume-ceph
          image: {{ .Values.wait_for.image }}
          imagePullPolicy: {{ template "imagePullPolicy" dict "root" . "context" .Values.wait_for }}
          args:
            - "pod"
            - "-lapp={{ template "volume-ceph_name" . }}"
      {{- end }}
      {{- if (index .Values "volume-gluster" "enabled") }}
        - name: wait-for-volume-gluster
          image: {{ .Values.wait_for.image }}
          imagePullPolicy: {{ template "imagePullPolicy" dict "root" . "context" .Values.wait_for }}
          args:
            - "pod"
            - "-lapp={{ template "volume-gluster_name" . }}"
      {{- end }}
      {{- if (index .Values "volume-swift" "enabled") }}
        - name: wait-for-volume-swift
          image: {{ .Values.wait_for.image }}
          imagePullPolicy: {{ template "imagePullPolicy" dict "root" . "context" .Values.wait_for }}
          args:
            - "pod"
            - "-lapp={{ template "volume-swift_name" . }}"
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ template "imagePullPolicy" dict "root" . }}
        {{- if or .Values.cpu .Values.memory }}
        resources:
          requests:
          {{- if .Values.cpu }}
            cpu: {{ .Values.cpu }}
          {{- end }}
          {{- if .Values.memory }}
            memory: {{ .Values.memory }}
          {{- end }}
        {{- end }}
        ports:
          - containerPort: 53
          - containerPort: 80
          - containerPort: 443
          - containerPort: 5555
          - containerPort: 5556
          - containerPort: 6665
          - containerPort: 6666
          - containerPort: 7443
          - containerPort: 8443
          - containerPort: 8876
          - containerPort: 8877
          - containerPort: 9443
        command:
          - "/bin/bash"
          - "-c"
          - >
            echo {{ template "fullname" . }}-{{ sub (.Values.oneprovider_nodes_count) 1 }} ;
            if [[ "$HOSTNAME" != {{ template "fullname" . }}-{{ sub (.Values.oneprovider_nodes_count) 1 }} ]]; then export ONEPANEL_BATCH_MODE="false" ; fi ;
            env ;
            {{- if .Values.sources }}
              while [ ! -f /tmp/sources_ready.txt ]; do   sleep 1; done ;
              export ONEPANEL_OVERRIDE=$(cat /tmp/sources_ready.txt) ;
            {{- end }}
            /root/oneprovider.sh ;
            cat /var/log/op_panel/info.log ;
            exit 1 ;
        lifecycle:
          preStop:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  op_panel stop ;
                  op_worker stop ;
                  cluster_manager stop ;
                  /etc/init.d/couchbase-server stop ;
                  pkill -f oneprovider.py ;
        readinessProbe:
          exec:
            command:
              - "/bin/bash"
              - "-c"
              - >
                onepanel_ready() { sleep 5 ; exit 0 ; } ;
                if [[ "$HOSTNAME" == {{ template "fullname" . }}-{{ sub (.Values.oneprovider_nodes_count) 1 }} ]]; then exit 0 ; else onepanel_ready ; fi ;
        env:
          - name: ONEPANEL_DEBUG_MODE
            value: {{ default "false" .Values.onepanel_debug_mode | quote }}
          - name: ONEPANEL_LOG_LEVEL
            value: {{ default "info" .Values.log_level | quote }}
          - name: ONEPANEL_GENERATE_TEST_WEB_CERT
            value: {{ default "false" .Values.onepanel_generate_test_web_cert | quote }}
          - name: ONEPANEL_GENERATED_CERT_DOMAIN
            value: "{{ template "service_url" . | default .Values.onepanel_generated_cert_domain }}"
          - name: ONEPANEL_TRUST_TEST_CA
            value: {{ default "false" .Values.onepanel_trust_test_ca | quote }}
          - name: ONEPANEL_BATCH_MODE
            value: {{ .Values.onepanel_batch_mode_enabled | quote }}
          - name: ONEPROVIDER_CONFIG
            valueFrom:
              configMapKeyRef:
                name: {{ template "fullname" . }}-config
                key: ONEPROVIDER_CONFIG
        volumeMounts:
          - name: config-map
            mountPath: /etc/op_panel/overlay.config
            subPath: panel-overlay.config
          - name: config-map
            mountPath: /etc/op_worker/overlay.config
            subPath:  worker-overlay.config
      {{- if (index .Values "generate-certificates" "enabled") }}
          - mountPath: /etc/op_panel/certs/web_key.pem
            subPath: tls.key
            name: tls
            readOnly: true
          - mountPath: /etc/op_panel/certs/web_cert.pem
            subPath: tls.crt
            name: tls
            readOnly: true
          - mountPath: /etc/op_panel/certs/web_chain.pem
            subPath: k8s.crt
            name: tls
            readOnly: true
          # Make onepanel trust k8s cert
          - mountPath: /etc/op_panel/cacerts/kubernetes.crt
            subPath: k8s.crt
            name: tls
            readOnly: true
          # Make system trust k8s cert
          - mountPath: /etc/ssl/certs/kubernetes.crt
            subPath: k8s.crt
            name: tls
            readOnly: true
      {{- end }}
      {{- if (index .Values "volume-nfs" "enabled") }}
          - mountPath: {{ index .Values "volume-nfs" "container_mount_path" }}
            name: nfs
      {{- end }}
      {{- if and (index .Values "volume-data-sync" "enabled") (eq (int .Values.oneprovider_nodes_count) 1) }}
        {{- range $volume := (index .Values "volume-data-sync" "volumes") }}
          - mountPath: /volumes/{{ $volume.name }}:shared
            name: {{ $volume.name }}
        {{- end }}
      {{- end }}
      {{- if and (index .Values "volume-data-sync" "enabled") (eq (int .Values.oneprovider_nodes_count) 1) }}
        {{- range $volume := (index .Values "volume-data-sync" "volumes") }}
      - name: {{ $volume.name }}
        image: {{ $volume.image }}
        imagePullPolicy: {{ template "imagePullPolicy" dict "root" $ "context" $volume }}
        command:
          - "/bin/sh"
          - "-c"
          - >
            mount -o bind {{ $volume.dataPath }} /{{ $volume.name }} ;
            {{- if $volume.readOnly }}
            mount -o remount,ro /{{ $volume.name }} ;
            {{- end }}
            {{- range $a_chown := $volume.chowns }}
            chown -R {{ $a_chown.user }}{{- if $a_chown.group }}:{{ $a_chown.group }}{{- end }} {{ $volume.dataPath }}/{{ $a_chown.path }} ;
            {{- end }}
            sleep 3600000 ;
        volumeMounts:
          - mountPath: /{{ $volume.name }}:shared
            name: {{ $volume.name }}
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        {{- end }}
      {{- end }}
      volumes:
      - name: config-map
        configMap:
          name: {{ template "fullname" . }}-config
    {{- if (index .Values "generate-certificates" "enabled") }}
      - name: tls
        secret:
          secretName: {{ template "fullname" . }}-secret-tls
    {{- end }}
    {{- if (index .Values "volume-nfs" "enabled") }}
      - name: nfs
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-nfs-pvc
    {{- end }}
      {{- if and (index .Values "volume-data-sync" "enabled") (eq (int .Values.oneprovider_nodes_count) 1) }}
        {{- range $volume := (index .Values "volume-data-sync" "volumes") }}
      - name: {{ $volume.name }}
        emptyDir: {}
        {{- end }}
      {{- end }}