# Default values for onedata-cli.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: onedata/rest-cli:20.02.12
imagePullPolicy: IfNotPresent

wait_for:
  image: groundnuty/k8s-wait-for:v1.5.1
  imagePullPolicy: IfNotPresent

# Wait for onezone service to start
wait_for_onezone:
  enabled: true

# The generalization of nodeSelector.
# Allows for more fine grained control over which
# nodes are selected by a kubernetes scheduler
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

# List of taints which are tolerated by the pods 
# when nodes are selected by a kubernetes scheduler
# https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# Specify a map of key-value pairs. For the pod 
# to be eligible to run on a node, the node 
# must have each of the indicated key-value pairs as labels
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}
